### ISSUE TITLE
 Using the MLE estimation methods on longitudinal data

### ISSUE THREAD

**Issue by cbundi** [shanjukta-nath/Homophily-Network-Influence#1]
Hi, I am trying to use your estimation methods specifically the  sarMLclassicZ, sarMLZ, sarMLZc on longitudinal data with the coefficient of influence, rho, as my variable of interest. However, the values I get produces biased estimates even when I substitute Uhat with U, the actual latent factors. Are the SAR estimation methods able to handle longitudinal response variable, Y or were there some assumptions you set for the methods to only handle simultaneous response variable Y?
I have attached the code I am currently using below, which is basically your simulation set up with minor changes at the network generating code, Y_0 and Y_1.

```
nodes = c(50,100,150,200,300,400,500,600,700,800)
comms = 3
d =3
d2 =2 
beta =c(1,2, 0.5)
theta = c(0.3,-0.4)
gamma = 0.1 
rho = 0.4 



estbeta<-list()
sebeta<-list()

for (m in 1:length(nodes)){
  meanprop<-rmultinom(nodes[m],1,rep(1/comms,comms))
  
  Bmat=matrix(c(0.7,0.2,0.3,0.2,0.8,0.25,0.3,0.25,0.75),3,3)
  spectra= eigen(Bmat)
  U= spectra$vectors[,1:d]%*%diag(sqrt(spectra$values[1:d]))
  
  
  Ubig = t(meanprop)%*%U
  
  Z= matrix(rnorm(2*nodes[m],0,0.5),nodes[m],2)
  Z[,1] = Z[,1]+ 2*Ubig[,1] + Ubig[,2] 
  Z[,2] = Z[,2] + Ubig[,1]+ Ubig[,3] 
  
  
  pmat<-t(meanprop)%*%Bmat%*%meanprop
  
  estbeta[[m]] = matrix(NA,4,200)
  sebeta[[m]] = matrix(NA,4,200)
  
  
  
  for ( i in 1:200){
    X= matrix(0,nodes[m],nodes[m])
    for(k in 1:(nodes[m]-1))
    {
      for(j in (k+1):nodes[m])
      {
        X[k,j]<-rbinom(1,1,pmat[k,j])
        X[j,k]<-X[k,j]
      }
    }
    
    D = rowSums(X)
    D[D<1]=1
    L = X/D
    
    Y_0 = c(Ubig%*%beta) + c(Z%*%theta) + rnorm(nodes[m],0,1)
    Y_1 = c(Ubig%*%beta) + c(Y_0*gamma) + c(rowSums(L%*%Y_0)*rho) + c(Z%*%theta) + rnorm(nodes[m],0,1)
    
    
    # No latent factor
    estclassic = sarMLclassicZ(Y=Y_1,L,X,Z)
    estbeta[[m]][1,i] = estclassic$influence 
    sebeta[[m]][1,i] = estclassic$SEinfluence
    
    # Uncorrected latent factor
    ests = sarMLZ(Y=Y_1,L,X,Z,d=3, U=Ubig)
    estbeta[[m]][2,i] = ests$influence  
    sebeta[[m]][2,i] = ests$SEinfluence
    
    # Bias corrected latent factor
    estmod = sarMLZc(Y=Y_1,L,X,Z,d=3,comms=3, U=Ubig)
    estbeta[[m]][3,i] = estmod$influence  
    sebeta[[m]][3,i] = estmod$SEinfluence
}
}
```

**Comment by shanjukta-nath** [comment]
Hi, 
We just updated the simulation.Rmd with the code for the longitudinal case (see section 3). Please take a look at it if you are able to replicate it in your setup. If there are further issues, please let us know.

**Comment by cbundi** [comment]
Hi,
Is it possible to use the MLE estimators instead  of the linear models used in section 3? I replicated this but the uncorrected and bias corrected latent factor estimators are still biased
```
nodes = c(50,100,150,200,250,300,400,500,600,700,800, 900, 1000)
comms = 4
d =2
d2 =2
beta =c(1,2)
rho=0.3

estbeta<-list()
sebeta<-list()
testbeta<-list() 


for (m in 1:length(nodes)){
  print(nodes[m])
  meanprop<-rmultinom(nodes[m],1,rep(1/comms,comms))
  
  U = matrix(c(0.7,0.1,0.2,0.5,0.2,0.6,0.2,0.5),4,2)
  Bmat = U%*%t(U)
  Ubig = t(meanprop)%*%U
  pmat<-t(meanprop)%*%Bmat%*%meanprop
  
  estbeta[[m]] = matrix(NA,4,200)
  sebeta[[m]] = matrix(NA,4,200)
  testbeta[[m]] = matrix(NA,4,200)
  
  for ( i in 1:200){
    X= matrix(0,nodes[m],nodes[m])
    for(k in 1:(nodes[m]-1))
    {
      for(j in (k+1):nodes[m])
      {
        X[k,j]<-rbinom(1,1,pmat[k,j])
        X[j,k]<-X[k,j]
      }
    }
    
    D = rowSums(X)
    D[D<1]=1
    L = X/D
    
    ## running it for 2 time periods
    
    Y_0 =  Ubig%*%beta + rnorm(nodes[m],0,1)
    Y_1 =  Ubig%*%beta + rho*L%*%Y_0 + 0.1*Y_0 + rnorm(nodes[m],0,1)
    
    ## Z contains two columns, the first one is the network influence
    Z=cbind(L%*%Y_0, Y_0)        #obs. var Z is PI, exclude Y_0
    
    
    # No latent factor
    estclassic = sarMLclassicZ(Y=Y_1,L,X,Z)
    estbeta[[m]][1,i] = estclassic$betacovariate[1]
    sebeta[[m]][1,i] = estclassic$SEbetacovariate[1]
    testbeta[[m]][,i] = estclassic$pvaluecovariate[1]#1 for stat significant 0 for not significant
    
    # Uncorr. latent factor
    ests = sarMLZ(Y=Y_1,L,X,Z,d=2, U=Ubig)
    estbeta[[m]][2,i] = ests$betacovariate[1]
    sebeta[[m]][2,i] = ests$SEbetacovariate[1]
      testbeta[[m]][2,i] = ests$pvaluecovariate[1]
      
    # Bias corr. latent factor
    estmod = sarMLZc(Y=Y_1,L,X,Z,d=2,comms=4, U=Ubig)
    estbeta[[m]][3,i] = estmod$betacovariate[1]
    sebeta[[m]][3,i] = estmod$SEbetacovariate[1]
    testbeta[[m]][3,i] = estmod$pvaluecovariate[1]
    
    # Correct linear model 
    regdata = data.frame(Y=Y_1,U=Ubig,Z=Z)
    betalm = lm(Y~Ubig+Z,data=regdata)
    estbeta[[m]][4,i] = summary(betalm)$coefficients["Z1", "Estimate"]
    sebeta[[m]][4,i] = summary(betalm)$coefficients["Z1", "Std. Error"]
    testbeta[[m]][4,i] = summary(betalm)$coefficients["Z1", "Pr(>|t|)"]
    
  }
}
```

**Comment by cbundi** [comment]
Hi,
I am trying to build a general MLE estimator that can work in the longitudinal case and I'm trying to replicate what you are doing here with the SAR estimators for simultaneous case. I know it's supposed to look like the OLS estimator in the end but I want to go through the MLE approach to it, while I know the answer should be the same. I am stuck, I can't replicate the minimization of rho. I don't understand how minimization using first and second derivative should change in the longitudinal case, could you help me figure it out.

**Comment by subhadeep1989** [comment]
Hi, yes our methodology for the longitudinal case is also based on correcting the score function as the simultaneous case. However, we did not write it in detail in the paper, since the method for longitudinal case boils down to linear regression for which the method is already well known. This paper developed the method:
Nakamura, T. (1990). Corrected score function for errors-in-variables models: Methodology and application to generalized linear models. Biometrika, 77(1), 127-137.
(available here: https://www.jstor.org/stable/2336055)
Our code follows the estimator proposed in the above paper for the longitudinal case. For the SAR model in the simultaneous case, such measurement error bias corrected estimators are not available in the literature - so we derived them in the paper.

**Comment by cbundi** [comment]
Oh I see, this clarified some things. Then the function you call ```lfreq()``` is the MLE approach while correcting the score function for longitudinal setting? If I wanted an MLE approach for uncorrected latent factor it would be this?
```
MLE_uncorr<-function(Y,X,Z,Uhat){
  nodes=length(Y)
  d2 = dim(Z)[2]

  ### Extraction of latent vectors from network adjacency matrix through SVD

  spectra<-svd(X)
  Uhat<-spectra$u[,1:d]%*%diag(sqrt(spectra$d[1:d]))
 
  ### Estimate the regression parameters
  MY = t(cbind(Uhat,Z))%*%Y
  MZW = t(cbind(Uhat,Z))%*%(cbind(Uhat,Z))
  betac  = as.matrix(solve(MZW))%*%MY
  hatY = cbind(Uhat,Z)%*%betac
  sigma = sqrt((sum((Y-hatY)^2))/(nodes - (d+d2)))
  sebetac = c(sigma)*sqrt(diag(solve(MZW)))

  ### Return bias corrected estimates of beta with standard error
  return(list(betac=betac,sebetac=sebetac, sigma=sigma))
}
```
Just to clarify, the SAR estimators are the MLE approach that can only work in simultaneous setting and cannot be generalized to longitudinal?

**Comment by subhadeep1989** [comment]
Yes, this is what you would do if you wanted to code up the estimator for uncorrected latent factor yourself. However, for uncorrected latent factors you could also just call the lm() function in R with cbind(Uhat,Z) as predictors and Y as response, which computes the exact same estimator - so you will get identical results. 

For the SAR model, things are a bit more complicated even in the uncorrected latent factors case. The MLE estimator is not the same as the least squares estimator. Our function sarMLZ() computes the MLE. The lagsarlm() function in the spatialreg package also computes the MLE for the uncorrected latent factor case (https://r-spatial.github.io/spatialreg/reference/ML_models.html) and gives identical results to our function sarMLZ(). However, we wrote the function ourselves because we needed to build bias correction on top of it. Our sarMLZc() function computes the estimator for the SAR model in bias corrected latent factor case. 

I hope this answers your questions :)

**Comment by cbundi** [comment]
Yes, thank you for your help!
